config/routes.rb
Rails.application.routes.draw do

    root    'pub/root#index'

    match   'api/oai/request'   => 'pub/api/oai#index', :format => 'xml', :via => [:get,:post]

    get     'api/info'              => 'pub/api/info#index',        :format => 'json'
    get     'api/info/oaipmh'                => 'pub/api/info#oaipmh',       :format => 'json'
    get     'api/info/oaipmh/year'           => 'pub/api/info#oaipmh_year',  :format => 'json'
    get     'api/info/oaipmh/month/(:month)' => 'pub/api/info#oaipmh_month', :format => 'json'

    get     'api/search/document'   => 'pub/api/search#document',   :format => 'xml'

    get     'api/list/:list_def_code/info'  => 'pub/api/info#list', :format => 'json'

    get     'api/statistics/all/month/:month/(:token)'          => 'pub/api/statistics#all_month',      :format => 'json'
    get     'api/statistics/document/:id/month/:month/(:token)' => 'pub/api/statistics#document_month', :format => 'json'
    get     'api/statistics/person/:id/month/:month/(:token)'   => 'pub/api/statistics#person_month',   :format => 'json'

    get     'api/statistics/all/monthly/(:token)'           => 'pub/api/statistics#all_monthly',      :format => 'json'
    get     'api/statistics/document/:id/monthly/(:token)'  => 'pub/api/statistics#document_monthly', :format => 'json'
    get     'api/statistics/person/:id/monthly/(:token)'    => 'pub/api/statistics#person_monthly',   :format => 'json'

    get     'api/statistics/all/(:token)'           => 'pub/api/statistics#all',      :format => 'json'
    get     'api/statistics/document/:id/(:token)'  => 'pub/api/statistics#document', :format => 'json'
    get     'api/statistics/person/:id/(:token)'    => 'pub/api/statistics#person',   :format => 'json'

    get     'api/count/:id'  => 'pub/api/misc_counts#show', :format => 'json'


    post     'api/post_data'    => 'pub/api/syslink#post_data'
    get      'api/get_data'     => 'pub/api/syslink#get_data'
    get      'api/get_co_data'  => 'pub/api/syslink#get_co_data'
    get      'api/id_search'    => 'pub/api/syslink#id_search'

    scope '(:locale)', constraints: { locale: /(en|ja)/ } do
    scope '(:logined)', constraints: { logined: :user } do

        devise_for :staffs, :skip => [:registrations]

        [{ name: nil,       prefix: 'pub' },
         { name: 'lim',     prefix: 'lim' },
         { name: 'pri',     prefix: 'pri' }].each do |layer|
        scope layer[:name], module: layer[:prefix], controller: 'root', as: layer[:name] || 'pub' do

            get     '/'                 => :index
            get     'p/:page'           => :index
            get     ':id'               => :index,  as: :item,  constraints: { id: /\w*\d+/ }
            get     'p/:page/:id'       => :index,              constraints: { id: /\d+/ }

            get     ':id/thumnail'      => :thumnail,   as: :thumnail, constraints: { id: /\d+/ }
            get     ':id/attach/:name'  => :attach,     as: :attach,   constraints: { id: /\d+/, :name => /[^\.\/][^\/]+/ }
            get     'metadata/:id'      => :index,      as: :metadata, constraints: { id: /\w*\d+/ }

            get     ':id/file'            => 'files#show_first',       as: :first_file,            constraints: { id: /\d+/ }
            get     ':id/file/thumnail'   => 'files#thumnail_first',   as: :first_file_thumnail,   constraints: { id: /\d+/ }

            get     'file/:document_id/:field_def_id/:id'            => 'files#show',       as: :file,           constraints: { document_id: /\d+/, field_def_id: /\d+/, id: /\d+/ }
            get     'file/:document_id/:field_def_id/:id/thumnail'   => 'files#thumnail',   as: :file_thumnail,  constraints: { document_id: /\d+/, field_def_id: /\d+/, id: /\d+/ }

            get     'contact_us'        => 'contact_us#index'
            post    'send_contact_us'   => 'contact_us#send_mail'
            get     'result_contact_us' => 'contact_us#result'

            scope 'page/:static_page_def_code', controller: :static_pages, as: :static_page do
                get     '/(:param1)/(:param2)/(:param3)/(:param4)/(:param5)'     => :index
            end

            scope 'search/', controller: :searches, as: :search do
                post    '/'                     => :search
                get     '/search'               => :search
                get     '/'                     => :index
                get     'p/:page'               => :index
                get     'item/:id'              => :index
                get     'p/:page/item/:id'      => :index
                get     'dl/:download_id'       => :index, :format => 'xml'
            end

            scope 'list/:list_def_code/', controller: :lists, as: :list do
                get     '/'                         => :index
                get     's/:search_query'           => :index, as: :search
                get     'p/:page'                   => :index
                get     'item/:id'                  => :index
                get     'p/:page/item/:id'          => :index
                get     'dl/:download_id'           => :index, :format => 'xml'

                scope ':level1', as: :level1 do
                    get     '/'                     => :level1
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level1
                    get     'item/:id'              => :level1
                    get     'p/:page/item/:id'      => :level1
                    get     'dl/:download_id'       => :level1, :format => 'xml'
                end

                scope ':level1/:level2', as: :level2 do
                    get     '/'                     => :level2
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level2
                    get     'item/:id'              => :level2
                    get     'p/:page/item/:id'      => :level2
                    get     'dl/:download_id'       => :level2, :format => 'xml'
                end

                scope ':level1/:level2/:level3', as: :level3 do
                    get     '/'                     => :level3
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level3
                    get     'item/:id'              => :level3
                    get     'p/:page/item/:id'      => :level3
                    get     'dl/:download_id'       => :level3, :format => 'xml'
                end

                scope ':level1/:level2/:level3/:level4', as: :level4 do
                    get     '/'                     => :level4
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level4
                    get     'item/:id'              => :level4
                    get     'p/:page/item/:id'      => :level4
                    get     'dl/:download_id'       => :level4, :format => 'xml'
                end

                scope ':level1/:level2/:level3/:level4/:level5', as: :level5 do
                    get     '/'                     => :level5
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level5
                    get     'item/:id'              => :level5
                    get     'p/:page/item/:id'      => :level5
                    get     'dl/:download_id'       => :level5, :format => 'xml'
                end
            end

            scope 'journal/:ej_journal_code', controller: :journals, as: :journal do
                get     '/'           => :journal
                get     'all_index'   => :all_index,   as: :all_index
                get     ':page_code'  => :static_page, as: :static_page

                scope ':volume/:issue', as: :voliss do
                    get     '/'                     => :voliss
                    get     'p/:page'               => :voliss
                    get     'dl/:download_id'       => :voliss, :format => 'xml'
                    get     'article/:id'           => :article, as: :article
                    get     'p/:page/article/:id'   => :article
                end
            end

        end
        end


        scope 'staff', as: :staff do
            get     '/'                     => 'pri_documents#index'
            post    '/'                     => 'pri_documents#search'
            get     'page/:page'            => 'pri_documents#index'
            get     'page/:page/item/:id'   => 'pri_documents#index'
            get     'dl/:download_id'       => 'pri_documents#index', :format => 'xml'

            get     'edit_password'         => 'passwords#edit'
            put     'update_password'       => 'passwords#update'

            resources :staffs, except: [:show]

            resources :custom_selects do
                resources :custom_select_values, except: [:index, :show] do
                    post    :search,    on: :collection
                    put     :up,        on: :member
                    put     :down,      on: :member
                end
            end

            get     'coverpage_settings'            => 'coverpage_settings#index'
            get     'coverpage_settings/edit'       => 'coverpage_settings#edit'
            patch   'coverpage_settings/update'     => 'coverpage_settings#update'

            scope 'view_settings', module: :view_settings, as: :view_setting do
                scope 'system', controller: :system, as: :system do
                    get     '/'             => :index
                    get     :edit
                    patch   :update
                    get     :param_form
                    get     :edit_top_page
                    patch   :update_top_page
                    put     :clear_cache
                    get     :edit_detail_view

app/models/staff.rb
#--
# Open Earmas
#
# Copyright (C) 2014 ENU Technologies
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

class Staff < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :lockable

    default_scope { order(:id) }

    validate  :check_ej_editor_role

    ROLE_BOOL_VALUE = ['管理', '一般']

    ROLE_ADMIN = 9
    ROLE_STAFF = 1
    ROLE_EJ_EDITOR = 2

    def admin?
        role == ROLE_ADMIN
    end

    def ej_editor?
        role == ROLE_EJ_EDITOR
    end

    def editable_ej_journal_def
        EjJournalDef.find_by(id: ej_journal_def_id)
    end

    def role_caption
        case role
        when ROLE_ADMIN
            '管理者'
        when ROLE_STAFF
            '一般ユーザ'
        when ROLE_EJ_EDITOR
            'EJ編集者'
        end
    end

private

    def check_ej_editor_role
        if role == ROLE_EJ_EDITOR && editable_ej_journal_def == nil
            errors.add(:ej_journal_def_id, "を指定してください。")
        end
    end

end

app/controllers/staffs_controller.rb
#--
# Open Earmas
#
# Copyright (C) 2014 ENU Technologies
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

class StaffsController < BaseAdminController

    before_action :check_staff_exists, except: [:index, :new, :create]

    def index
        @staffs = Staff.all
    end

    def new
        @staff = Staff.new
        @staff.role = Staff::ROLE_STAFF
    end

    def create
        @staff = Staff.new(request_params)

        if @staff.save
            redirect_to staff_staffs_url, notice: 'ユーザを作成しました。'
        else
            render action: 'new'
        end
    end

    def edit
    end

    def update
        params[:staff].delete(:password) if params[:staff][:password].blank?
        params[:staff].delete(:password_confirmation) if params[:staff][:password].blank? and params[:staff][:password_confirmation].blank?

        update_action_block('edit', 'staff', 'ユーザの更新に失敗しました。') do
            if @staff.update(request_params)
                if Staff.where(role: Staff::ROLE_ADMIN).size < 1
                    raise DataCheckException, "管理者は最低でも一人は必要です"
                end

                redirect_to staff_staffs_url, notice: 'ユーザを更新しました。'
            else
                render action: 'edit'
            end
        end
    end

    def destroy
        redirect_block(staff_staffs_url, 'staff', 'ユーザの削除に失敗しました。') do
            @staff.destroy!
            if Staff.where(role: Staff::ROLE_ADMIN).size < 1
                raise DataCheckException, "管理者は最低でも一人は必要です"
            end

            redirect_to staff_staffs_url, notice: 'ユーザを削除しました。'
        end
    end


private

    def check_staff_exists
        @staff = Staff.find(params[:id])
    end

    def request_params
        params.require(:staff).permit(
            :email,
            :role,
            :ej_journal_def_id,
            :password,
            :password_confirmation)
    end

end

app/views/staffs/_form.html.erb
<%= form_for [:staff, @staff], html: { class: "form-horizontal", role: "form" } do |f| %>
    <% if @staff.errors.any? %>
        <div id="error_explanation">
            <div><%= t("errors.messages.not_saved", :count => @staff.errors.count, :resource => 'データ') %></div>
            <ul>
                <% @staff.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :email, "メールアドレス", class: "col-md-6 control-label" %>
        <div class="col-md-18"><%= f.text_field :email, class: 'form-control' %></div>
    </div>

    <div class="form-group">
        <%= f.label :role, "権限", class: "col-md-6 control-label" %>
        <div class="col-md-18">
            <label class="radio-inline">
                <%= f.radio_button :role, Staff::ROLE_ADMIN %> 管理者
            </label>
            <label class="radio-inline">
                <%= f.radio_button :role, Staff::ROLE_STAFF %> 一般ユーザ
            </label>
            <label class="radio-inline">
                <%= f.radio_button :role, Staff::ROLE_EJ_EDITOR %> EJ編集者
            </label>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :ej_journal_def_id, "編集可能EJ（EJ編集者のみ）", class: "col-md-6 control-label" %>
        <div class="col-md-18"><%= f.select :ej_journal_def_id, EjJournalDef.all.map{|t| [t.code, t.id] }, { include_blank: '設定しない'}, {class: 'form-control'} %></div>
    </div>

    <div class="form-group">
        <%= f.label :password, "パスワード", class: "col-md-6 control-label" %>
        <div class="col-md-18"><%= f.password_field :password, class: 'form-control', :autocomplete => "off", placeholder: "leave blank if you don't want to change it" %></div>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation, "パスワード(確認)", class: "col-md-6 control-label" %>
        <div class="col-md-18"><%= f.password_field :password_confirmation, class: 'form-control' %></div>
    </div>

    <div class="form_button_container bottom">
        <%= f.submit '保存', class: ['btn', 'btn-primary'] %>
    </div>

<% end %>

app/views/staffs/edit.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'ユーザ管理', staff_staffs_path %></li>
    <li class="active">ユーザ 修正</li>
</ol>

<div class="page-header">
    <h1>ユーザ 修正</h1>
</div>

<%= render 'form' %>

app/views/staffs/index.html.erb
<div class="page-header">
  <h1>ユーザ管理</h1>
</div>

<div class="panel panel-default">
    <table class="table table-bordered">
        <colgroup>
            <col class="col-xs-4">
            <col class="col-xs-2">
            <col class="col-xs-2">
            <col class="col-xs-1">
            <col class="col-xs-1">
        </colgroup>
        <thead>
            <tr>
                <th>メールアドレス</th>
                <th>権限</th>
                <th>編集可能EJ</th>
                <th>修正</th>
                <th>削除</th>
            </tr>
        </thead>
        <tbody>
            <% @staffs.each do |staff| %>
                <tr>
                    <td><%= staff.email %></td>
                    <td><%= staff.role_caption %></td>
                    <td><%= staff.editable_ej_journal_def.try(:code) || '未設定' %></td>
                    <td><%= link_to '修正', edit_staff_staff_path(staff) %></td>
                    <td><%= link_to '削除', staff_staff_path(staff), method: :delete, data: { confirm: 'Are you sure?' }, class: ['text-danger'] %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div class="panel-footer">
        <div class="form_button_container">
            <%= link_to '追加', new_staff_staff_path, class: ['btn', 'btn-primary', 'btn-xs'] %>
        </div>
    </div>
</div>

app/views/staffs/new.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'ユーザ管理', staff_staffs_path %></li>
    <li class="active">ユーザ 新規作成</li>
</ol>

<div class="page-header">
    <h1>ユーザ 新規作成</h1>
</div>

<%= render 'form' %>