config/routes.rb
Rails.application.routes.draw do

    root    'pub/root#index'

    match   'api/oai/request'   => 'pub/api/oai#index', :format => 'xml', :via => [:get,:post]

    get     'api/info'              => 'pub/api/info#index',        :format => 'json'
    get     'api/info/oaipmh'                => 'pub/api/info#oaipmh',       :format => 'json'
    get     'api/info/oaipmh/year'           => 'pub/api/info#oaipmh_year',  :format => 'json'
    get     'api/info/oaipmh/month/(:month)' => 'pub/api/info#oaipmh_month', :format => 'json'

    get     'api/search/document'   => 'pub/api/search#document',   :format => 'xml'

    get     'api/list/:list_def_code/info'  => 'pub/api/info#list', :format => 'json'

    get     'api/statistics/all/month/:month/(:token)'          => 'pub/api/statistics#all_month',      :format => 'json'
    get     'api/statistics/document/:id/month/:month/(:token)' => 'pub/api/statistics#document_month', :format => 'json'
    get     'api/statistics/person/:id/month/:month/(:token)'   => 'pub/api/statistics#person_month',   :format => 'json'

    get     'api/statistics/all/monthly/(:token)'           => 'pub/api/statistics#all_monthly',      :format => 'json'
    get     'api/statistics/document/:id/monthly/(:token)'  => 'pub/api/statistics#document_monthly', :format => 'json'
    get     'api/statistics/person/:id/monthly/(:token)'    => 'pub/api/statistics#person_monthly',   :format => 'json'

    get     'api/statistics/all/(:token)'           => 'pub/api/statistics#all',      :format => 'json'
    get     'api/statistics/document/:id/(:token)'  => 'pub/api/statistics#document', :format => 'json'
    get     'api/statistics/person/:id/(:token)'    => 'pub/api/statistics#person',   :format => 'json'

    get     'api/count/:id'  => 'pub/api/misc_counts#show', :format => 'json'


    post     'api/post_data'    => 'pub/api/syslink#post_data'
    get      'api/get_data'     => 'pub/api/syslink#get_data'
    get      'api/get_co_data'  => 'pub/api/syslink#get_co_data'
    get      'api/id_search'    => 'pub/api/syslink#id_search'

    scope '(:locale)', constraints: { locale: /(en|ja)/ } do
    scope '(:logined)', constraints: { logined: :user } do

        devise_for :staffs, :skip => [:registrations]

        [{ name: nil,       prefix: 'pub' },
         { name: 'lim',     prefix: 'lim' },
         { name: 'pri',     prefix: 'pri' }].each do |layer|
        scope layer[:name], module: layer[:prefix], controller: 'root', as: layer[:name] || 'pub' do

            get     '/'                 => :index
            get     'p/:page'           => :index
            get     ':id'               => :index,  as: :item,  constraints: { id: /\w*\d+/ }
            get     'p/:page/:id'       => :index,              constraints: { id: /\d+/ }

            get     ':id/thumnail'      => :thumnail,   as: :thumnail, constraints: { id: /\d+/ }
            get     ':id/attach/:name'  => :attach,     as: :attach,   constraints: { id: /\d+/, :name => /[^\.\/][^\/]+/ }
            get     'metadata/:id'      => :index,      as: :metadata, constraints: { id: /\w*\d+/ }

            get     ':id/file'            => 'files#show_first',       as: :first_file,            constraints: { id: /\d+/ }
            get     ':id/file/thumnail'   => 'files#thumnail_first',   as: :first_file_thumnail,   constraints: { id: /\d+/ }

            get     'file/:document_id/:field_def_id/:id'            => 'files#show',       as: :file,           constraints: { document_id: /\d+/, field_def_id: /\d+/, id: /\d+/ }
            get     'file/:document_id/:field_def_id/:id/thumnail'   => 'files#thumnail',   as: :file_thumnail,  constraints: { document_id: /\d+/, field_def_id: /\d+/, id: /\d+/ }

            get     'contact_us'        => 'contact_us#index'
            post    'send_contact_us'   => 'contact_us#send_mail'
            get     'result_contact_us' => 'contact_us#result'

            scope 'page/:static_page_def_code', controller: :static_pages, as: :static_page do
                get     '/(:param1)/(:param2)/(:param3)/(:param4)/(:param5)'     => :index
            end

            scope 'search/', controller: :searches, as: :search do
                post    '/'                     => :search
                get     '/search'               => :search
                get     '/'                     => :index
                get     'p/:page'               => :index
                get     'item/:id'              => :index
                get     'p/:page/item/:id'      => :index
                get     'dl/:download_id'       => :index, :format => 'xml'
            end

            scope 'list/:list_def_code/', controller: :lists, as: :list do
                get     '/'                         => :index
                get     's/:search_query'           => :index, as: :search
                get     'p/:page'                   => :index
                get     'item/:id'                  => :index
                get     'p/:page/item/:id'          => :index
                get     'dl/:download_id'           => :index, :format => 'xml'

                scope ':level1', as: :level1 do
                    get     '/'                     => :level1
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level1
                    get     'item/:id'              => :level1
                    get     'p/:page/item/:id'      => :level1
                    get     'dl/:download_id'       => :level1, :format => 'xml'
                end

                scope ':level1/:level2', as: :level2 do
                    get     '/'                     => :level2
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level2
                    get     'item/:id'              => :level2
                    get     'p/:page/item/:id'      => :level2
                    get     'dl/:download_id'       => :level2, :format => 'xml'
                end

                scope ':level1/:level2/:level3', as: :level3 do
                    get     '/'                     => :level3
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level3
                    get     'item/:id'              => :level3
                    get     'p/:page/item/:id'      => :level3
                    get     'dl/:download_id'       => :level3, :format => 'xml'
                end

                scope ':level1/:level2/:level3/:level4', as: :level4 do
                    get     '/'                     => :level4
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level4
                    get     'item/:id'              => :level4
                    get     'p/:page/item/:id'      => :level4
                    get     'dl/:download_id'       => :level4, :format => 'xml'
                end

                scope ':level1/:level2/:level3/:level4/:level5', as: :level5 do
                    get     '/'                     => :level5
                    get     's/:search_query'       => :index, as: :search
                    get     'p/:page'               => :level5
                    get     'item/:id'              => :level5
                    get     'p/:page/item/:id'      => :level5
                    get     'dl/:download_id'       => :level5, :format => 'xml'
                end
            end

            scope 'journal/:ej_journal_code', controller: :journals, as: :journal do
                get     '/'           => :journal
                get     'all_index'   => :all_index,   as: :all_index
                get     ':page_code'  => :static_page, as: :static_page

                scope ':volume/:issue', as: :voliss do
                    get     '/'                     => :voliss
                    get     'p/:page'               => :voliss
                    get     'dl/:download_id'       => :voliss, :format => 'xml'
                    get     'article/:id'           => :article, as: :article
                    get     'p/:page/article/:id'   => :article
                end
            end

        end
        end


        scope 'staff', as: :staff do
            get     '/'                     => 'pri_documents#index'
            post    '/'                     => 'pri_documents#search'
            get     'page/:page'            => 'pri_documents#index'
            get     'page/:page/item/:id'   => 'pri_documents#index'
            get     'dl/:download_id'       => 'pri_documents#index', :format => 'xml'

            get     'edit_password'         => 'passwords#edit'
            put     'update_password'       => 'passwords#update'

            resources :staffs, except: [:show]

            resources :custom_selects do
                resources :custom_select_values, except: [:index, :show] do
                    post    :search,    on: :collection
                    put     :up,        on: :member
                    put     :down,      on: :member
                end
            end

            get     'coverpage_settings'            => 'coverpage_settings#index'
            get     'coverpage_settings/edit'       => 'coverpage_settings#edit'
            patch   'coverpage_settings/update'     => 'coverpage_settings#update'

            scope 'view_settings', module: :view_settings, as: :view_setting do
                scope 'system', controller: :system, as: :system do
                    get     '/'             => :index
                    get     :edit
                    patch   :update
                    get     :param_form
                    get     :edit_top_page
                    patch   :update_top_page
                    put     :clear_cache
                    get     :edit_detail_view

app/controllers/ej_editors/ej_static_page_defs_controller.rb
#--
# Open Earmas
#
# Copyright (C) 2014 Hiroshima University, ENU Technologies
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

class EjEditors::EjStaticPageDefsController < EjEditors::BaseController
    include OrderHolder

    before_action :check_ej_static_page_def_exists, except: [:new, :create]

    def new
        @ej_static_page_def = EjStaticPageDef.new
        @ej_static_page_def.set_default_child
    end

    def create
        @ej_static_page_def = EjStaticPageDef.new(request_params)
        @ej_static_page_def.ej_journal_def_id = @editable_ej_journal_def.id
        @ej_static_page_def.sort_index = EjStaticPageDef.where(ej_journal_def_id: @editable_ej_journal_def.id).maximum(:sort_index)
        @ej_static_page_def.sort_index = @ej_static_page_def.sort_index && @ej_static_page_def.sort_index + 1 || 1

        if @ej_static_page_def.save
            redirect_to staff_ej_editors_ej_journal_show_url, notice: '静的ページを作成しました。'
        else
            render action: 'new'
        end
    end

    def show
    end

    def edit
        @ej_static_page_def.set_default_child
    end

    def update
        @ej_static_page_def.assign_attributes(request_params)

        if @ej_static_page_def.save
            redirect_to staff_ej_editors_ej_journal_show_url, notice: '静的ページを更新しました。'
        else
            render action: 'edit'
        end
    end

    def destroy
        redirect_block(staff_ej_editors_ej_journal_show_url, 'ej_static_page_def', '静的ページの削除に失敗しました。') do
            @ej_static_page_def.destroy
            redirect_to staff_ej_editors_ej_journal_show_url, notice: '静的ページを削除しました。'
        end
    end

    def up
        move_up(@editable_ej_journal_def.static_page_defs.to_a, @ej_static_page_def)

        redirect_to staff_ej_editors_ej_journal_show_url, notice: '静的ページを移動しました。'
    end

    def down
        move_down(@editable_ej_journal_def.static_page_defs.to_a, @ej_static_page_def)

        redirect_to staff_ej_editors_ej_journal_show_url, notice: '静的ページを移動しました。'
    end

private

    def check_ej_static_page_def_exists
        @ej_static_page_def = @editable_ej_journal_def.static_page_defs.find(params[:id])
    end

    def request_params
        params.require(:ej_static_page_def).permit(
            :code,
            :visible,
            :caption_ja,
            :caption_en,
            :journal_static_view_type_id,
            :journal_static_sub_header_view_type_id,
            :journal_static_sub_footer_view_type_id,
            { journal_static_html_set_def_attributes: [:id, :body_top_html_string_ja, :body_top_html_string_en, :body_bottom_html_string_ja, :body_bottom_html_string_en, :header_parts_id, :footer_parts_id, :right_side_parts_id] },
            :body_main_html_string_ja,
            :body_main_html_string_en)
    end
end

app/controllers/ej_static_page_defs_controller.rb
#--
# Open Earmas
#
# Copyright (C) 2014 Hiroshima University, ENU Technologies
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

class EjStaticPageDefsController < BaseAdminController
    include OrderHolder

    before_action :check_ej_def_exists
    before_action :check_ej_journal_def_exists
    before_action :check_ej_static_page_def_exists, except: [:new, :create]

    def new
        @ej_static_page_def = EjStaticPageDef.new
        @ej_static_page_def.set_default_child
    end

    def create
        @ej_static_page_def = EjStaticPageDef.new(request_params)
        @ej_static_page_def.ej_journal_def_id = @ej_journal_def.id
        @ej_static_page_def.sort_index = EjStaticPageDef.where(ej_journal_def_id: @ej_journal_def.id).maximum(:sort_index)
        @ej_static_page_def.sort_index = @ej_static_page_def.sort_index && @ej_static_page_def.sort_index + 1 || 1

        if @ej_static_page_def.save
            redirect_to staff_view_setting_ej_journal_show_path(@ej_journal_def), notice: '静的ページを作成しました。'
        else
            render action: 'new'
        end
    end

    def show
    end

    def edit
        @ej_static_page_def.set_default_child
    end

    def update
        @ej_static_page_def.assign_attributes(request_params)

        if @ej_static_page_def.save
            redirect_to staff_view_setting_ej_journal_show_path(@ej_journal_def), notice: '静的ページを更新しました。'
        else
            render action: 'edit'
        end
    end

    def destroy
        redirect_block(staff_view_setting_ej_journal_show_path(@ej_journal_def), 'ej_static_page_def', '静的ページの削除に失敗しました。') do
            @ej_static_page_def.destroy
            redirect_to staff_view_setting_ej_journal_show_path(@ej_journal_def), notice: '静的ページを削除しました。'
        end
    end

    def up
        move_up(@ej_journal_def.static_page_defs.to_a, @ej_static_page_def)

        redirect_to staff_view_setting_ej_journal_show_path(@ej_journal_def), notice: '静的ページを移動しました。'
    end

    def down
        move_down(@ej_journal_def.static_page_defs.to_a, @ej_static_page_def)

        redirect_to staff_view_setting_ej_journal_show_path(@ej_journal_def), notice: '静的ページを移動しました。'
    end

private

    def check_ej_def_exists
        @ej_def = EjDef.find(params[:ej_def_id])
    end

    def check_ej_journal_def_exists
        @ej_journal_def = @ej_def.journal_defs.find(params[:ej_journal_def_id])
    end

    def check_ej_static_page_def_exists
        @ej_static_page_def = @ej_journal_def.static_page_defs.find(params[:id])
    end

    def request_params
        params.require(:ej_static_page_def).permit(
            :code,
            :visible,
            :caption_ja,
            :caption_en,
            :journal_static_view_type_id,
            :journal_static_sub_header_view_type_id,
            :journal_static_sub_footer_view_type_id,
            { journal_static_html_set_def_attributes: [:id, :body_top_html_string_ja, :body_top_html_string_en, :body_bottom_html_string_ja, :body_bottom_html_string_en, :header_parts_id, :footer_parts_id, :right_side_parts_id] },
            :body_main_html_string_ja,
            :body_main_html_string_en)
    end
end

app/views/ej_static_page_defs/_form.html.erb
<%= form_for [:staff, @ej_def, @ej_journal_def, @ej_static_page_def], html: { class: "form-horizontal", role: "form" } do |f| %>
    <% if @ej_static_page_def.errors.any? %>
        <div id="error_explanation">
            <div><%= t("errors.messages.not_saved", :count => @ej_static_page_def.errors.count, :resource => 'データ') %></div>
            <ul>
                <% @ej_static_page_def.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :code, "URLのパス", class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.text_field :code, class: 'form-control' %></div>
    </div>

    <div class="form-group">
        <%= f.label :caption_ja, "表示名(日本語)", class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.text_field :caption_ja, class: 'form-control' %></div>
    </div>

    <div class="form-group">
        <%= f.label :caption_en, "表示名(英語)", class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.text_field :caption_en, class: 'form-control' %></div>
    </div>

    <div class="form-group">
        <%= f.label :journal_static_view_type_id, "表示形式", class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.select :journal_static_view_type_id, show_journal_static_view_type_option, {}, { class: 'form-control' } %></div>
    </div>

    <div class="form-group">
        <%= f.label :journal_static_sub_header_view_type_id, "サブヘッダ形式", class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.select :journal_static_sub_header_view_type_id, show_journal_static_sub_header_view_type_option, {}, { class: 'form-control' } %></div>
    </div>

    <div class="form-group">
        <%= f.label :journal_static_sub_footer_view_type_id, "サブフッタ形式", class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.select :journal_static_sub_footer_view_type_id, show_journal_static_sub_footer_view_type_option, {}, { class: 'form-control' } %></div>
    </div>

    <div class="form-group">
        <%= f.label :body_main_html_string_ja, 'メイン (日本語)', class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.text_area :body_main_html_string_ja, rows: 10, class: 'form-control' %></div>
    </div>
    <div class="form-group">
        <%= f.label :body_main_html_string_en, 'メイン (英語)', class: "col-md-5 control-label" %>
        <div class="col-md-19"><%= f.text_area :body_main_html_string_en, rows: 10, class: 'form-control' %></div>
    </div>

    <%= f.fields_for :journal_static_html_set_def do |f| %>
        <%= render partial: 'html_set_defs/form', locals: { f: f } %>
    <% end %>

    <div class="form_button_container bottom">
        <%= f.submit '保存', class: ['btn', 'btn-primary'] %>
    </div>

<% end %>

app/views/ej_static_page_defs/_index.html.erb
<div class="page-header">
    <h2>静的ページ</h2>
</div>

<div class="panel panel-default">
    <table class="table table-bordered">
        <colgroup>
            <col class="col-xs-2">
            <col class="col-xs-3">
            <col class="col-xs-3">
            <col class="col-xs-1">
            <col class="col-xs-1">
            <col class="col-xs-1">
        </colgroup>
        <thead>
            <tr>
                <th>URLのパス</th>
                <th>日本語名</th>
                <th>英語名</th>
                <th>移動</th>
                <th>修正</th>
                <th>削除</th>
            </tr>
        </thead>

        <tbody>
        <% @ej_journal_def.static_page_defs.each do |static_page_def| %>
            <tr>
                <td><%= link_to static_page_def.code, pri_journal_static_page_path(@ej_journal_def.code, static_page_def.code) %></td>
                <td><%= static_page_def.caption_ja %></td>
                <td><%= static_page_def.caption_en %></td>
                <td>
                    <%= link_to up_staff_ej_def_ej_journal_def_ej_static_page_def_path(@ej_def, @ej_journal_def, static_page_def), method: :put, class: ['btn', 'btn-default', 'btn-xs'] do %>
                        <span class="glyphicon glyphicon-arrow-up"></span><% end %>
                    <%= link_to down_staff_ej_def_ej_journal_def_ej_static_page_def_path(@ej_def, @ej_journal_def, static_page_def), method: :put, class: ['btn', 'btn-default', 'btn-xs'] do %>
                        <span class="glyphicon glyphicon-arrow-down"></span><% end %>
                </td>
                <td><%= link_to '修正', edit_staff_ej_def_ej_journal_def_ej_static_page_def_path(@ej_def, @ej_journal_def, static_page_def) %></td>
                <td><%= link_to '削除', [:staff, @ej_def, @ej_journal_def, static_page_def], method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
    <div class="panel-footer">
        <div class="form_button_container">
            <%= link_to '追加', new_staff_ej_def_ej_journal_def_ej_static_page_def_path(@ej_def, @ej_journal_def), class: ['btn', 'btn-primary', 'btn-xs'] %>
        </div>
    </div>
</div>

app/views/ej_static_page_defs/edit.html.erb
<ol class="breadcrumb">
    <li><%= link_to '雑誌 管理', staff_ej_defs_path %></li>
    <li><%= link_to '雑誌グループ 詳細', staff_ej_def_path(@ej_def) %></li>
    <li><%= link_to @ej_journal_def.code + '詳細', staff_ej_def_ej_journal_def_path(@ej_def, @ej_journal_def) %></li>
    <li class="active"><%= show_caption(@ej_static_page_def) %> 修正</li>
</ol>

<div class="page-header">
    <h1><%= show_caption(@ej_static_page_def) %> 修正</h1>
</div>

<%= render 'form' %>

app/views/ej_static_page_defs/new.html.erb
<ol class="breadcrumb">
    <li><%= link_to '雑誌 管理', staff_ej_defs_path %></li>
    <li><%= link_to '雑誌グループ 詳細', staff_ej_def_path(@ej_def) %></li>
    <li><%= link_to @ej_journal_def.code + '詳細', staff_ej_def_ej_journal_def_path(@ej_def, @ej_journal_def) %></li>
    <li class="active">静的ページ 新規作成</li>
</ol>

<div class="page-header">
    <h1>静的ページ 新規作成</h1>
</div>

<%= render 'form' %>